apiVersion: v1
kind: Service
metadata:
  name: apm-service-proxy
spec:
#  type: NodePort
  selector:
    app: apm-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
#      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-service-deployment
  labels:
    app: apm-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apm-service
  template:
    metadata:
      labels:
        app: apm-service
    spec:
      containers:
        - name: apm-service
          image: mnolan98/apm-service:0.0.4
          ports:
            - containerPort: 3000

