apiVersion: v1
kind: Service
metadata:
  name: apm-service-proxy
spec:
#  type: NodePort
  selector:
    app: apm-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
#      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-service-deployment
  labels:
    app: apm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-service
  template:
    metadata:
      labels:
        app: apm-service
    spec:
      containers:
        - name: apm-service
          image: mnolan98/apm-service:0.0.10
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          env:
          - name: MONGO_DB_URL
            value: "test-mongodb-0.test-mongodb-svc.mongodb.svc.cluster.local:27017,test-mongodb-1.test-mongodb-svc.mongodb.svc.cluster.local:27017,test-mongodb-2.test-mongodb-svc.mongodb.svc.cluster.local:27017"
#            value: "test-mongodb-svc.mongodb:27017"
          - name: MONGO_REPL_SET
            value: "replicaSet=mongodb/test-mongodb"
          ports:
            - containerPort: 3000

