apiVersion: v1
kind: Service
metadata:
  name: apm-svc-mongodb-nonprod-svc
  labels:
# This matches the app in the rc, not the rc
    app: test-mongodb
spec:
  type: NodePort
# types are 
# ClusterIP for a stable internal cluster ip
# NodePort for exposing the the port outside the cluster, on top of stable internal ip
# LoadBalancer integrates NodePort with cloud-based load balancer
  ports:
  - port: 27017
    nodePort: 30004
    protocol: TCP
  selector:
    app: test-mongodb